### ISSUE TITLE
Tether fud

### ISSUE THREAD

**Issue by era-coder** [pox/EndTheFUD#11]
The most Recent assertion : https://tether.to/wp-content/uploads/2021/04/tether-assurance-mar-2021-2.pdf
Recent breakdown of reserves: https://tether.to/wp-content/uploads/2021/05/tether-march-31-2021-reserves-breakdown.pdf

**Comment by pox** [comment]
Those are useful links, but I'm not sure it's right to categorize them as anti-FUD articles. So I'm not sure how to add them. Perhaps on a separate page dedicated to Tether?
