### ISSUE TITLE
Some links no longer work

### ISSUE THREAD

**Issue by 9mido** [pox/EndTheFUD#20]
Use https://www.deadlinkchecker.com/ to check to see which links no longer work.

Status | URL | Source link text
-- | -- | --
404 Not Found | https://endthefud.org/pow | endthefud.org/PoW
404 Not Found | https://medium.com/john-pfeffer/an-institutional-investors-take-on-cryptoassets-69042115890 | An (Institutional) Investor’s Take on Cryptoassets
503 Service Unavailable | https://www.amazon.com/Thank-God-Bitcoin-Corruption-Redemption/dp/1641991216/ref=sr_1_1?dchild=1&keywords=thank+god+for+bitcoin&qid=1607152012&sr=8-1 | Thank God for Bitcoin
404 Not Found | https://endthefud.org/pos | endthefud.org/PoS
403 Forbidden | https://blog.coinbase.com/fact-check-is-bitcoin-mining-environmentally-unfriendly-3559823af6f1 | FACT CHECK: Is Bitcoin mining environmentally unfriendly?
-1 Not found: A connection with the server could not be established | https://btcco2.org/ | btcCO2.org
-1 Timeout | https://btcco2.com/ | btcCO2.com
-1 Timeout | https://shitcoin.review/ | shitcoin.review

**Comment by pox** [comment]
Thank you for bringing this to my attention. Good to know this web site, I'll definitely use it in the future.
Will fix the broken links.

**Comment by 9mido** [comment]
Awesome thanks.

**Comment by pox** [comment]
All broken links fixed. A couple were false positives (some domains seem to block the bot).

**Comment by 9mido** [comment]
Thanks for the fast turnaround. There are a bunch of broken link checkers you could use. Search broken link checkers on your search engine. 

If you use python, you could use something like https://wummel.github.io/linkchecker/

**Comment by pox** [comment]
Good idea.

You feedback is awesome. I hope you watch the repo and keep adding your input.

**Comment by lingmann** [comment]
Hi @pox it might be useful to integrate a Github action broken linker checker such as [Broken Link Checker Action](https://github.com/marketplace/actions/broken-link-checker-action). I haven't used this particular one, but it seemed to be a decent candidate after doing a very quick google search. Would you be open to a PR to add a Github action that does automatic broken link checking and reporting? And if so, do you have any preferences on how it might work? Thanks for working on this awesome project!!

**Comment by pox** [comment]
Great idea @lingmann. This action can be triggered on both PRs and with cron. Go right ahead and add it if you want. Otherwise I might just do it. :)
