### ISSUE TITLE
"bitcoin Is not backed by anything"

### ISSUE THREAD

**Issue by era-coder** [pox/EndTheFUD#3]
https://armantheparman.com/what-is-the-true-value-of-bitcoin/

**Comment by pox** [comment]
It's a nice article, but I'm not quite sure it counters any FUD specifically. More of a general overview of how to price bitcoin. The "bitcoin is not backed by anything" FUD, in particular, is something you hear from people who typically think money must have some underlying asset behind it (e.g. gold) or force (e.g. US gov), and the article doesn't really focus on this at all.

**Comment by era-coder** [comment]
Feel free to close this issue
