### ISSUE TITLE
Please add 'Bitcoin Has No Intrinsic Value' by Arman The Parman

### ISSUE THREAD

**Issue by 84adam** [pox/EndTheFUD#31]
Please consider this new article, "Bitcoin Has No Intrinsic Value" (A logical rebuttal to one of the most common misconceptions about Bitcoin, by Arman The Parman), for addition under the topic of “No intrinsic value”, “Bitcoin is a bubble”.

Link: https://bitcoinreserve.com/blog/bitcoin-has-no-intrinsic-value

Good discussion of the concept of intrinsic value (whether it even exists) as well as summarizing Mises' Regression Theorem and Aristotle’s Properties of Money.

**Comment by pox** [comment]
yikes.
on value: 
> We sometimes can put a number to it (using money), to help us rank the things we value.

Mises already rolling over in his grave, conflating ordinal with cardinal :)

lol but it's a solid article. Adding it.
