### ISSUE TITLE
Something specifically debunking "raises climate above 2°C"

### ISSUE THREAD

**Issue by lingmann** [pox/EndTheFUD#32]
I know there are a lot of great articles already debunking all the energy FUD, but wondering if it would be worthwhile to add another top-level energy category which specifically debunks Mora Et. al, Greenpeace, and the World Economic Forum propaganda?

I don't have a specific article recommendation yet, so this is more of a place-holder for me and to see if anyone has some thoughts. There is additional information coming out about how the Mora paper was created and who was behind it. For example: 

- Regarding Mora et. al - [paper was written by a class of undergraduates](https://twitter.com/DamienSomerset/status/1519399857600966656), there are serious flaws in the logic which can be easily identified with even basic levels of understanding of how Bitcoin works, and finally it has been debunked by other academic papers.
- Regarding Greenpeace / WEF video - very sensationalistic providing no data or evidence. I thought this was a nice contrast: https://twitter.com/thecryptoc0up1e/status/1508962213016576009
- A "nice to have" - article would also address WEF and Greenpeace conflicts of interest (participation by [Ethereum foundation](https://www.weforum.org/agenda/authors/aya-miyaguchi), investment and funding by [Brad Garlinghouse](https://www.weforum.org/people/brad-garlinghouse) who made $billions off of XRP, etc.)

**Comment by pox** [comment]
I honestly don't see how these recent pieces stand out. There's always another hit piece by incompetent journalists. In a few months no one will remember the Greenpeace campaign.

**Comment by lingmann** [comment]
Thanks for the feedback @pox. Yeah, I tend to agree that this particular campaign will not live long, but in my observation there is a broader false narrative that has firmly anchored itself in the minds of so many I talk to... and that is: "Bitcoin is bad for the environment and wastes energy." It's like they have heard it so many times, that there is no longer even a question in their mind whether it is true or not...

But that is a separate issue and adding a new section to EndTheFud will not necessarily help with that... Closing this issue and will keep thinking about ways to fight the FUD. :)
