### ISSUE TITLE
Add New Video Resource Debunking digieconomics fud

### ISSUE THREAD

**Issue by Fiach-Dubh** [pox/EndTheFUD#34]
Debunking Digiconomist Bitcoin Mining Energy FUD & False Data Reported By Mainstream News Outlets (Ben Gagnon Chief Mining Officer of Bitfarms) 

https://youtu.be/lDhCvNFUDvo

**Comment by pox** [comment]
Thank you. Probably won't be adding it because the focus is on articles, not videos. The site probably isn't the right format for aggregating videos.

**Comment by Fiach-Dubh** [comment]
fair enough, the last three slides in this deck focus on the video, but i dont think thats enough https://bitcoinminingcouncil.com/wp-content/uploads/2022/07/2022.07.19-BMC-Presentation-Q2-22-Presentation.pdf

**Comment by pox** [comment]
Thanks for understanding.
