### ISSUE TITLE
dead btcenergy.org domain

### ISSUE THREAD

**Issue by marcelcook** [pox/EndTheFUD#40]
Was about to raise a PR to remove the dead btcenergy.org domain, but it looks like you already did this yourself at the end of Nov. 

Just needs pushing to the site, as it still appears?

Great resource btw :)

**Comment by pox** [comment]
Thank you. Fixed now
https://github.com/pox/EndTheFUD/commit/90767ed8fe02c35cbd12ca8081768aa4939b03db
